Paths:
  path: "/model_checkpoints"
  work_path: ""
  load_path: None
  load_T: None

Anneal_params:
  schedule: "linear"
  reps: 1
  Temperature: 1.
  T_min: 0.
  N_warmup: 200
  N_anneal: 3000
  N_equil: 10
  eval_observations: 5

TrainMode: "PPO"

Train_params:
  masking: False
  pruning: True
  device: 0
  seed: 0
  lr: 1e-4
  lr_alpha: 0.2
  lr_schedule: "cosine"
  n_basis_states: 25
  H_batch_size: 25
  distributed: False
  batch_epochs: 1

  PPO:
    pl_param: 0.5
    vl_param: 0.5
    clip_value: 0.1
    lam: 0.95
    alpha: 0.05
    updates_per_iteration: 1
    mini_Nb: 10
    mini_Hb: 10
    mini_Sb: 8
    time_horizon: 10
    mov_avrg: 0.2

Test_params:
  eval_on_test: True
  n_test_graphs: 100

Ising_params:
  centrality: False
  self_loops: True
  IsingMode: "MaxCutSparse"
  shuffle_seed: 123
  graph_padding_factor: 1.2
  compl_graph_padding_factor: 4
  sampled_sites: 2
  alpha: 1.
  ext_field: False
  trivial: False
  pos_embeddings: False
  gamma: 0.
  normed: False
  normed_H_graph: False
  node_embedding_type: "None" ### or eigenvalues
  edge_embedding_type: False
  n_rand_nodes: 6 ### or alternative number of eigenvectors/eigenvalues
  sorting: False

  ordering: "BFS"  ## choice between BFS DFS
  reversed_disjoint_graph_ordering: False
  EnergyFunction: "MaxCut"


Network_params:
  layer_norm: True
  network_type: "GNN"
  policy_MLP_features: [ 120,64,2 ]
  value_MLP_features: [ 120,64,1 ]
  RNNs:
    nh: 120
    n_layers: 3
  GNNs:
    ### edge update flag
    GNN_name: "newEncoder_embedding"
    global_aggr: "sum"
    local_aggr: "sum" # (not implemented yet)
    edge_updates: False
    mode: "linear"
    message_MLP_features: [120,120]
    node_MLP_features: [120, 120]
    edge_MLP_features: [64,64]
    n_GNN_layers: 3
    encode_node_features: [64]
    encode_edge_features: [64]
    policy_global_features: True
    value_global_features: True


project: "NoProject"
group: "NoGroup"
job_type: "NoJob"

Save_settings:
  save_params: True
  wandb: True
  save_mode: "best"

